

x-airflow-common: &airflow-common
  image: apache/airflow:slim-2.9.3-python3.11
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-metadata-db/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
    
    DB_HOST: ${DB_HOST}
    DB_PORT: ${DB_PORT}
    DB_NAME: ${DB_NAME}
    DB_USER: ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
    DB_SSLMODE: ${DB_SSLMODE}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - airflow-logs:/opt/airflow/logs
    - .:/opt/airflow/project  
  depends_on:
    - airflow-metadata-db

services:
  airflow-metadata-db:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-metadata:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install --no-cache-dir -r /opt/airflow/project/requirements.txt
        airflow db migrate
        airflow users create --username airflow --password airflow \
          --firstname Groupe --lastname AQI --role Admin --email aqi@example.com

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: bash -c "pip install --no-cache-dir -r /opt/airflow/project/requirements.txt && airflow scheduler"
    restart: always

volumes:
  airflow-metadata:
  airflow-logs: